package modelos;
// Generated 31 ene. 2021 21:38:34 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {
	private int employeeNumber;
	private Employees employees;
	private Offices offices;
	private String lastName;
	private String firstName;
	private String extension;
	private String email;
	private String jobTitle;
	private Set<Employees> employeeses = new HashSet<Employees>(0);
	private Set<Customers> customerses = new HashSet<Customers>(0);

	public Employees() {
	}

	public Employees(int employeeNumber, Offices offices, String lastName, String firstName, String extension,
			String email, String jobTitle) {
		this.employeeNumber = employeeNumber;
		this.offices = offices;
		this.lastName = lastName;
		this.firstName = firstName;
		this.extension = extension;
		this.email = email;
		this.jobTitle = jobTitle;
	}

	public Employees(int employeeNumber, Employees employees, Offices offices, String lastName, String firstName,
			String extension, String email, String jobTitle, Set employeeses, Set customerses) {
		this.employeeNumber = employeeNumber;
		this.employees = employees;
		this.offices = offices;
		this.lastName = lastName;
		this.firstName = firstName;
		this.extension = extension;
		this.email = email;
		this.jobTitle = jobTitle;
		this.employeeses = employeeses;
		this.customerses = customerses;
	}

	public int getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(int employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public Offices getOffices() {
		return this.offices;
	}

	public void setOffices(Offices offices) {
		this.offices = offices;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public Set getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set employeeses) {
		this.employeeses = employeeses;
	}

	public Set getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set customerses) {
		this.customerses = customerses;
	}

}
