package modelos;
// Generated 31 ene. 2021 21:38:34 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Payments generated by hbm2java
 */
public class Payments implements java.io.Serializable {
	private PaymentsId id;
	private Customers customers;
	private Date paymentDate;
	private BigDecimal amount;

	public Payments() {
	}

	public Payments(PaymentsId id, Customers customers, Date paymentDate, BigDecimal amount) {
		this.id = id;
		this.customers = customers;
		this.paymentDate = paymentDate;
		tt = amount;
	}

	public PaymentsImhis.amouners(Customers customers) {
		this.customers = customers;
	}
	d getId() {
		return this.id;
	}

	public void setId(PaymentsId id) {
		this.id = id;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCusto
	public Date getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

}
